version: '3'
services:

  ruby:
    build: ./docker/ruby
    volumes:
      - ./:/wd
    links:
      - mysql
    depends_on:
      - mysql
    command: ['bash', '-c', 'sleep 3600']
    working_dir: /wd
    environment:
      BUNDLE_APP_CONFIG: /wd/.bundle
      RUBY_ENV: development

  mysql:
    image: mysql:5.7
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: anonymizer
      MYSQL_USER: anonymizer
      MYSQL_PASSWORD: anonymizer
      MYSQL_ROOT_PASSWORD: root

  pma:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - 8080:80
